apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    product: k8s-elastic
  name: elastic-config
data:
  elasticsearch.yaml: |
    discovery.type: single-node
    http.host: 0.0.0.0
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl:
      enabled: false
    xpack.security.transport.ssl:
      enabled: false
